### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by inter-proger** [centrifugal/centrifuge-ios#12]
Please update for Xcode 9 / Swift 4 support.

**Comment by mogol** [comment]
Hi, thanks for the request,
I will update in a couple of days

**Comment by mogol** [comment]
I have recently started porting. 👍

**Comment by makcimyc92** [comment]
Hi, do you still plan to upgrade to swift 4?

**Comment by mogol** [comment]
Hey, I updated code, but found an issue with https://github.com/tidwall/SwiftWebSocket . It has no release with Swift4. It blocks me right now. I couldn't create valid pod spec file. One of solution is moving to another web socket library, but it takes a while. I hope SwiftWebSocket will publish version with swift4 https://github.com/tidwall/SwiftWebSocket/pull/87

**Comment by sld** [comment]
Lets become the backers of this issue: https://www.bountysource.com/issues/50661435-swift-4-support.
Now it has 17$ bounty :)

**Comment by mogol** [comment]
Hey all,
I am sorry for inconvenience. I will consider  migration to another socket library and come back with results after this weekend.

**Comment by mogol** [comment]
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  CentrifugeiOS (4.0.0) successfully published
 📅  January 14th, 20:10
 🌎  https://cocoapods.org/pods/CentrifugeiOS
 👍  Tell your friends!
--------------------------------------------------------------------------------
