### ISSUE TITLE
Reconnect after the internet switch on

### ISSUE THREAD

**Issue by a1k89** [centrifugal/centrifuge-ios#15]
Some issue after I switch off and switch on the internet connection - websocket connection is lose. May I set a reconnect to centrifugo server? Or maybe have a some other way? thanks

**Comment by mogol** [comment]
If connection is lost, ` func client(_ client: CentrifugeClient, didReceiveError error: NSError)` method of CentrifugeClientDelegate would be called 

Currently there is no way to get the reason of disconnect, except checking localizedDescription. 
For your case, it's "The operation couldn’t be completed. Socket is not connected". 

I will add new method to handle disconnection gracefully and pass received errors from socket.
For your case again, the error is
```
Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected" UserInfo={_kCFStreamErrorCodeKey=57, _kCFStreamErrorDomainKey=1}
```

Reconnection should be done manually, when you received corresponding notifications from system.

**Comment by mogol** [comment]
I have pushed new pod version 5.0.1 with changes in error processing.
So now you can check errors via `func client(_ client: CentrifugeClient, didDisconnectWithError error: Error)` and handle them properly.

After internet appears again use normal flow, eg connect/subscribe etc

**Comment by a1k89** [comment]
Thanks a lot.
Yeah, now it's work very good!
Also, when application started, I set 2 notifications: UIApplicationDidEnterBackground, and UIApplicationWillEnterForeground.
When UIApplicationDidEnterBackground - client.disconnect()
When UIApplicationWillEnterForeground - client.connect() and subscribe to channel.
