### ISSUE TITLE
Why such assertionFailures?

### ISSUE THREAD

**Issue by sld** [centrifugal/centrifuge-ios#17]
Hello!

I'd like to know why there is such assertionFailure cases?
For example:
https://github.com/centrifugal/centrifuge-ios/blob/f8bf07ed108ccbc3543b8db2d3c4010406626d0a/CentrifugeiOS/Classes/CentrifugeClientImpl.swift#L156

This may happen when centrifugo server is not available. So it seems not good to fail even in the debug mode.

Thanks!

**Comment by mogol** [comment]
Not sure, but  it looks ok to me that a client should receive one of Error or Message (not both nil). 

> This may happen when centrifugo server is not available.

imo the client should get an error in this case, if not - it could be a bug 🌮
