### ISSUE TITLE
Centrifugo client silently fails after centrifugo server restart

### ISSUE THREAD

**Issue by sld** [centrifugal/centrifuge-ios#19]
CentrifugeiOS (4.0.0), release build.

1. Run ios app with centrifugo client - everything works fine.
2. Restart centrifugo server in the backend.
3. Centrifugo client in the ios app silently fails - there is no logs and debug print for subscribe, join, leave handlers outputs nothing.
4. Restarting ios apps solves the problem.

What may cause the problem?

**Comment by mogol** [comment]
I tried on 5 and 4 versions, there are callbacks with errors in both cases.
Could you provide steps to reproduce ?

**Comment by sld** [comment]
Thanks, restarting centrifugo server is ok.

I found that the problem was in restarting nginx. Still investigating it.

**Comment by mogol** [comment]
I am closing the issue. 
If you will meet the issue again, feel free to reopen or create new one. 

Thanks
