### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by lennathe** [centrifugal/centrifuge-ios#4]
Hi,

Is this not compatible with project using swift 3?
I have difficulties since my project is written in swift 3, I installed it with cocoapods but almost all the code return error even after I set Use Legacy Swift Language Version -> Yes 
Sometimes it returns error "... CentrifugeiOS compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64.."
Any help will be much appreciated.

Thanks

**Comment by mogol** [comment]
Hey @lennathe,
Sorry for inconvenience 
I will check soon

**Comment by mogol** [comment]
> 🚀  CentrifugeiOS (3.0.0) successfully published

Thanks !

**Comment by lennathe** [comment]
Hi @mogol thanks for the update!
