### ISSUE TITLE
Secret must not be used directly from client

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifuge-ios#8]
@mogol just realized that iOS client uses Centrifugo secret key on client side. It's insecure as it can only be known by Centrifugo server and application backend.

I.e.

```swift
let timestamp = "\(Int(NSDate().timeIntervalSince1970))"

let creds = CentrifugeCredentials(secret: secret, user: user, timestamp: timestamp)
let url = "wss://centrifugo.herokuapp.com/connection/websocket"
client = Centrifuge.client(url: url, creds: creds, delegate: self)
```

Must be sth like this:

```
let creds = CentrifugeCredentials(token: token, user: user, timestamp: timestamp, info: info)
let url = "wss://centrifugo.herokuapp.com/connection/websocket"
client = Centrifuge.client(url: url, creds: creds, delegate: self)
```

Where `token`, `user`, `timestamp` and `info` come from app backend. It's up to library users how to get these credentials from app backend.

**Comment by mogol** [comment]
Hey,
what is insecure in client's implementation ?
Should I rename secret to token? 
Creds has `info` field with default value nil. You still can
```swift
let creds = CentrifugeCredentials(secret: secret, user: user, timestamp: timestamp, info: info)
let url = "wss://centrifugo.herokuapp.com/connection/websocket"
client = Centrifuge.client(url: url, creds: creds, delegate: self)
```

**Comment by mogol** [comment]
```swift
public struct CentrifugeCredentials {
    let secret : String
    let user : String
    let timestamp : String
    let info: String?
    
    public init(secret: String, user: String, timestamp:String, info: String? = nil) {
        self.secret = secret
        self.user = user
        self.timestamp = timestamp
        self.info = info
    }
}
```

**Comment by FZambia** [comment]
As far as I understand secret is not token here. See [this](https://github.com/centrifugal/centrifuge-ios/blob/cc6af46632b65654c9bf0d2caa69a488fcf2bea7/CentrifugeiOS/Classes/Builder/CentrifugeClientMessageBuilderImpl.swift#L31) line where connect message params created - it generates token on client side using secret key from credentials. This is secret key which can't be shared with client in production scenarios - app backend generates token based on user, timestamp and info and iOS application asks backend for generated credentials before connecting to Centrifugo (it's up to user of library to decide how he will get these credentials from backend - HTTP request for example).

[This](https://github.com/centrifugal/centrifuge-ios/blob/cc6af46632b65654c9bf0d2caa69a488fcf2bea7/CentrifugeiOS/Classes/Builder/CentrifugeClientMessageBuilderImpl.swift#L91) function can be exported as public API but just as helper function for those who want to build token on client side (during development for example).

**Comment by FZambia** [comment]
Something like this:
```swift
public struct CentrifugeCredentials {
    let token : String
    let user : String
    let timestamp : String
    let info: String?
    
    public init(token: String, user: String, timestamp: String, info: String? = nil) {
        self.token = token
        self.user = user
        self.timestamp = timestamp
        self.info = info
    }
}
```

And generating connect params will be:

```swift
    func buildConnectMessage(credentials: CentrifugeCredentials) -> CentrifugeClientMessage {
        
        let user = credentials.user, timestamp = credentials.timestamp, token = credentials.token
        
        var params = ["user" : user,
                      "timestamp" : timestamp,
                      "token" : token]
        
        if let info = credentials.info {
            params["info"] = info
        }
        
        return buildMessage(method: .Connect, params: params)
    }
```

And move `func createToken(string: String, key: String) -> String` to top level so users could still generate token on client side for experimenting with Centrifugo.

**Comment by mogol** [comment]
Got it 👍

**Comment by mogol** [comment]
🚀  CentrifugeiOS (3.1.0) successfully published

**Comment by FZambia** [comment]
@mogol thanks a lot!
